### ISSUE TITLE
Time picker is not displayed in upper right corner

### ISSUE THREAD

**Issue by ageld** [kibana-community/kibana4-static#1]
I wonder if I am doing something wrong.  My Kibana+Elasticsearch+Logstash are installed on Ubuntu 14.04 server.  I tried both 32-bit and 64-bit Kibana, however, when I go into Overview (or any other mode) time picker is not displayed in the upper right corner of the screen.  How can I fix the issue?

**Comment by Asimov4** [comment]
I am not able to repro. The static version of Kibana 4 works as expected for me.
Are their any errors in the browser console that you can share here?

**Comment by ageld** [comment]
I am at total loss.  I replicated EVERYTHING I have in the lab in production: version of elasticsearch, version of kibana.  I continue having this issue.  The timepicker is not displayed and logs are displayed in kibana in earliest to latest order, instead of in latest to earliest order.  The configuration is all the same.  The version of Java is the same.  I thought that the problem was with the client (I use Ubuntu laptop in the lab and windows 7 laptop in production).  I connected Ubuntu laptop to production network and it did not show the timepicker.  I have no idea how to troubleshoot this further.  ANY ideas would be highly appreciated. 

Please, advise.  I want to deploy ELK in production, but this issue precludes me from doing so.

Regards,

Alek 

Date: Tue, 31 Mar 2015 22:28:43 -0700

**Comment by ageld** [comment]
My own mistake... I did not point to the Time field @timestamp.  As soon as I did it, everything started working.

Sorry... Just started learning ELK.

Thanks a lot for your reply to me.

Regards,

Alek

Date: Tue, 31 Mar 2015 22:28:43 -0700

**Comment by Asimov4** [comment]
No problem! I'll mark this as closed.
