### ISSUE TITLE
Kibana: Unknown error while connecting to Elasticsearch

### ISSUE THREAD

**Issue by molychnCHN** [kibana-community/kibana4-static#13]
Hi，
Thank for your static project, but now I have a question about the elasticsearch.
I have run the elasticsearch.bat in DOS windows, but the kibana page still warning about "Kibana: Unknown error while connecting to Elasticsearch".
How can I solve it ?

**Comment by oleg-nenashev** [comment]
1) Are you sure you use Kibana0static?
2) Are you sure that connection details point to the right ES location?

**Comment by molychnCHN** [comment]
Thank you for your reply me so quickly.
1) I do not know what the Kibana0static is, I just download the project of kibana-static from this url :https://github.com/kibana-community/kibana4-static.
2) I am sure that connection detail point to the right ES location (localhost:9200),but it warn me that "XMLHttpRequest cannot load http://localhost:9200/?_=1463384879103. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'file://' is therefore not allowed access."

**Comment by oleg-nenashev** [comment]
Which Elasticsearch version do you use? Does it have a configured security or access filtering?
Anyway, please attach the Elasticsearch log

**Comment by oleg-nenashev** [comment]
BTW, if you want to use Kibana as a standalone application, my recommendation would be to use official Kibana releases from https://www.elastic.co/products/kibana.

This project is a version, which allows embedding Kibana as a client-side-only application. But it is not a Kibana baseline

**Comment by molychnCHN** [comment]
Thank you for your advice, I'll think about it
