### ISSUE TITLE
Kibana Split My message

### ISSUE THREAD

**Issue by Git-Rajkumar** [kibana-community/kibana4-static#16]
I am working on EFK. I push chat message to elasticsearch and view to kinba 4. i view pie chat using message field.

   Kibana Split my message to space wise then take each as a message then show it. 

For example  -> "This is RK"  Kibana split this one mesasge to space wise take a three message , I need to get this message to one message how to get this?   For Reference  https://ibin.co/2kcLCYq8rZBH.png

**Comment by oleg-nenashev** [comment]
It is not a Kibana issue.
You should set the "not_analyzed" flag in Elasticsearch index mapping.
See https://www.elastic.co/guide/en/elasticsearch/guide/current/mapping-intro.html
