### ISSUE TITLE
Courier Fetch Error: unhandled courier request error: [illegal_argument_exception] explicit index in multi get is not allowed

### ISSUE THREAD

**Issue by mohantnr** [kibana-community/kibana4-static#17]
I am getting error in Kibana after enabling rest.action.multi.allow_explicit_index: false in elasticsearch.yml.  How to address this issue in kibana-4.5.1?

Regards
Mohan

**Comment by oleg-nenashev** [comment]
@mohantnr 
I suppose it's an issue with the common Kibana project: https://github.com/elastic/kibana
Kibana Static is far from the 4.5.1 version
