### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by jarviszeng-zjc** [kibana-community/kibana4-static#3]
Kibana: Unknown error while connecting to Elasticsearch.

Please help.

**Comment by Asimov4** [comment]
Can you share the version of Elasticsearch that you are using as well as the error log details?

**Comment by jarviszeng-zjc** [comment]
Thank you for your attention.
My Elasticserach version is 1.4.4. And I can found any log for Elasticsearch.
Here are something I see after open kibana.
![2015-05-29 10 23 34](https://cloud.githubusercontent.com/assets/5196427/7875249/18cf1b5a-05ed-11e5-9e65-333aa0c2ff2f.jpg)

**Comment by jbolster** [comment]
I had the same issue. For me, it turned out that ElasticSearch needed to have cors enabled. See this gist: https://gist.github.com/rmoff/379e6ce46eb128110f38

Hopefully that helps!

**Comment by jarviszeng-zjc** [comment]
It works! Thanks.
