### ISSUE TITLE
Update to Kibana 4.2.0+ in order to support Elasticsearch 2.x

### ISSUE THREAD

**Issue by oleg-nenashev** [kibana-community/kibana4-static#9]
Hello,

In one project i'd like to migrate my database to Elasticsearch 2.x. I use Kibana, which is fully compatible with Elasticsearch 2.0 starting from 4.2.0. Unfortunately the kibana-static project now supports Kibana 4.1.2. Upgrade of kibana4-static requires pulling the public folder from the main Kibana repository.
- Are there any plans/ETAs regarding the kibana4-static upgrade?
- If no, is there a guideline describing the update procedure? From what I see in the commit history, it's not just a copy-paste activity

CC @kibanaco and @Asimov4 

Thanks in advance,

**Comment by oleg-nenashev** [comment]
I cannot change the assignee, but I'm working on it

**Comment by Asimov4** [comment]
Sorry! A bit behind on email updates but this is great! Thanks for picking it up.
The process is kind of documented in this old issue: https://github.com/elastic/kibana/issues/1628 and yes; it is mostly a copy pasting game.

**Comment by oleg-nenashev** [comment]
Unfortunately, the structure of Kibana 4.2..4.4 became much more complicated, so a straightforward copy-paste does not seem to be realistic.

I've posted a PR with a workaround solution: https://github.com/kibana-community/kibana4-static/pull/10 . At least it allows using ES 2.0 for particular cases. All my dashboards are operating correctly with this fix.

**Comment by oleg-nenashev** [comment]
I'm closing this issue, because ES 2.0 is de-factor working. By the way, it would be still useful to support features from newer Kinaba versions.
